streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': ['user://themes/materials-library', 'user://themes/quark']
enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: false
header-dark: false
header-transparent: false
sticky-footer: true
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/materials-library/images/logo/matlib-logo.svg:
    name: matlib-logo.svg
    type: image/svg+xml
    size: 3172
    path: user/themes/materials-library/images/logo/matlib-logo.svg
